server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: ticket-service
  datasource:
    url: ${TICKET_DB_URL:jdbc:postgresql://localhost:5432/ticketmaster?currentSchema=tickets_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: tickets_schema
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: tickets_schema
    liquibase-schema: tickets_schema
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: ticket-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

springdoc:
  servers:
    - url: http://localhost:8090
      description: API Gateway
  open-api:
    servers:
      - url: http://localhost:8090
        description: API Gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true