server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: event-service
  datasource:
    url: ${EVENT_DB_URL:jdbc:postgresql://localhost:5432/ticketmaster?currentSchema=events_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: events_schema
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/event/changelog-master.xml
    default-schema: events_schema
    liquibase-schema: events_schema
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  servers:
    - url: http://localhost:8090
      description: API Gateway
  open-api:
    servers:
      - url: http://localhost:8090
        description: API Gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
